---
name: hammer

info: General purpose correcting tool.

roles:
- smash
- unjoin

stats:
  size: 2
  durable: 3
  effort: 2
  efficacy: 3

blueprint:
- [1, 0, 0]
- [2, 0, 0]
- [2, 0, 0]

components:
- hammer-head
- stick